### ISSUE TITLE
No 'alt' attribute for buto-lightbox-play-icon

### ISSUE THREAD

**Issue by danielbassmg** [ButoVideo/buto-lightbox#21]
The image of the play button with class 'buto-lightbox-play-icon' has no alt attribute and there doesn't appear to be a way of setting one. The only way to resolve the issue is assigning an alt attribute using jquery after the elements have loaded, but this is very wasteful and slow.

This fails WCAG H37 accessibility guideline: https://www.w3.org/TR/WCAG20-TECHS/H37.html and prevents our site from passing accessibility testing.

**Comment by agentreno** [comment]
Thanks for letting us know @danielbassmg, we have added the alt attribute.

**Comment by danielbassmg** [comment]
Thanks @agentreno
